# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44e8b9ef1ae9a79206989e9ddb0062164c7650269b51e4e9727e222bf764f3cd8faa9004e3d1d96dbb7bb734efc54e68acac09d42b6e0a0d50c3c41b4869760f

test:
  secret_key_base: 16f384a266311ed46b9c83e5ac319a275adbd7d2725fe25dfb28d9cafe18b9a56a3745822825dd6bdd6766e3e56dc25ed0ffc7615289cad489076b7c6030ee33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
